version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "7wells/repo-privacy-check-public*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
